name: Deploy to Google App Engine

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploying...
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add Firebase Service Account 
      env:
        FIREBASE_FILES: ${{ vars.DEV_FIREBASE_SA }}
      run: |
        echo $FIREBASE_FILES
        echo $FIREBASE_FILES > serviceAccountKey.json
        cat serviceAccountKey.json

    - name: Add GCP Service Account
      env:
        GCP_FILES: ${{ vars.DEV_GCP_CREDENTIALS }}
      run: |
        echo $GCP_FILES
        echo $GCP_FILES > service_gcp.json
        cat service_gcp.json

    - name: GCP Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.DEV_GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'