name: Deploy to Google App Engine (PRODUCTION)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploying Production...
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add Firebase Service Account 
      env:
        FIREBASE_FILES: ${{ secrets.PROD_FIREBASE_SA }}
      run: |
        echo $FIREBASE_FILES
        echo $FIREBASE_FILES > serviceAccountKey.json

    - name: Add GCP Service Account
      env:
        GCP_FILES: ${{ secrets.PROD_GCP_CREDENTIALS }}
      run: |
        echo $GCP_FILES
        echo $GCP_FILES > service_gcp.json

    - name: Add app.yaml
      env:
        API_KEY: ${{ secrets.PROD_API_KEY }}
        BUCKET_NAME: ${{ secrets.PROD_BUCKET_NAME }}
        PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
        FOOD_PREDICTIONS_API: ${{ secrets.PROD_FOOD_PREDICTIONS_API }}

      run: |
        cp app.example.yaml app.yaml
        sed -i "s/your-api-key/$API_KEY/g" app.yaml
        sed -i "s/your-project-id/$PROJECT_ID/g" app.yaml
        sed -i "s/your-bucket-name/$BUCKET_NAME/g" app.yaml
        sed -i "s|your-ml-food-predictions-api|${FOOD_PREDICTIONS_API//\//\\/}|g" app.yaml

    - name: GCP Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.PROD_GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Deploy to GAE
      id: deploy
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        deliverables: app.yaml

    - name: Test Endpoint
      run: 'curl "${{ steps.deploy.outputs.url }}"'