name: Code Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]  
  
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Start Checking
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."

